variables:
  NPM_NEXUS_SERVICE_CONNECTION: ns-npm-nexus
  NPM_WORKING_DIR: 'rest-api-public/typescript'
  NPM_CACHE_CONFIG: $(Pipeline.Workspace)/.npm
  AWS_SERVICE_CONNECTION_DEV: aws-awsome-dev # Fill in the name of your own service connection here
  AWS_SERVICE_CONNECTION_STG: <FILLMEIN>
  AWS_SERVICE_CONNECTION_PRD: <FILLMEIN>

trigger:
  branches:
    include:
      - '*'

resources:
  repositories:
    - repository: ns-shared-guard-rules
      type: git
      name: NSCAWS/ns-shared-guard-rules
    - repository: shared-templates
      name: NSPAAS/azure-devops-templates
      type: git
      ref: refs/tags/main_20220921.1

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: build
    jobs:
      - job: build
        steps:
          - task: Cache@2
            inputs:
              key: 'npm | "$(Agent.OS)" | $(Build.SourcesDirectory)/$(NPM_WORKING_DIR)/package-lock.json'
              path: $(NPM_CACHE_CONFIG)
            displayName: Cache NPM packages
          - task: Npm@1
            displayName: npm:ci
            inputs:
              command: custom
              customCommand: 'ci --cache $(NPM_CACHE_CONFIG) --omit=dev'
              workingDir: ${{ variables.NPM_WORKING_DIR }}
              customEndpoint: $(NPM_NEXUS_SERVICE_CONNECTION)
          - task: Npm@1
            displayName: npm:build
            inputs:
              command: custom
              workingDir: ${{ variables.NPM_WORKING_DIR }}
              customCommand: 'run build'
              customEndpoint: $(NPM_NEXUS_SERVICE_CONNECTION)
          - task: Npm@1
            displayName: npm:lint
            inputs:
              command: custom
              customCommand: 'run lint'
              workingDir: ${{ variables.NPM_WORKING_DIR }}
              customEndpoint: $(NPM_NEXUS_SERVICE_CONNECTION)

  - stage: qa
    jobs:
      - job: ci
        steps:
          - task: Npm@1
            displayName: npm:ci
            inputs:
              command: custom
              customCommand: 'ci --cache $(NPM_CACHE_CONFIG) --omit=dev'
              workingDir: ${{ variables.NPM_WORKING_DIR }}
              customEndpoint: $(NPM_NEXUS_SERVICE_CONNECTION)
          - task: Npm@1
            displayName: unit tests
            inputs:
              command: custom
              workingDir: ${{ variables.NPM_WORKING_DIR }}
              customCommand: 'run test -- test/unit'
              customEndpoint: $(NPM_NEXUS_SERVICE_CONNECTION)
          - template: steps/test/code-analysis/sonarqube.yml@shared-templates
            parameters:
              serviceConnection: 'CRAWS SonarQube EE P'
              scannerMode: CLI
              configMode: file
              configFile: ${{ variables.NPM_WORKING_DIR }}/sonar-project.properties
              pollingTimeoutSec: 600
          - task: Npm@1
            displayName: npm:audit
            inputs:
              command: custom
              workingDir: ${{ variables.NPM_WORKING_DIR }}
              customCommand: audit --audit-level=high --omit=dev
              customEndpoint: $(NPM_NEXUS_SERVICE_CONNECTION)

  - stage: 'deploy_feature'
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    jobs:
      - job: deploy
        steps:
          - task: Npm@1
            displayName: npm ci
            inputs:
              command: custom
              customCommand: 'ci --cache $(NPM_CACHE_CONFIG) --omit=dev'
              workingDir: $(NPM_WORKING_DIR)
              customEndpoint: $(NPM_NEXUS_SERVICE_CONNECTION)

        #  - task: AWSShellScript@1
        #    displayName: deploy:feature
        #    inputs:
        #      awsCredentials: ${{ variables.AWS_SERVICE_CONNECTION_DEV }}
        #      regionName: 'eu-west-1'
        #      scriptType: 'inline'
        #      workingDirectory: ${{ variables.NPM_WORKING_DIR }}
        #      inlineScript: |
        #        npx cdk deploy --ci -c feature=$(Build.SourceBranchName) -c config=dev -c genericConfig=generic -c Repository=$(Build.Repository.Name) -c Pipeline=$(Build.DefinitionName) --all --require-approval never


  - stage: 'deploy_dev'
    jobs:
      - job: deploy
        steps:
          - task: Npm@1
            displayName: npm ci --cache $(NPM_CACHE_CONFIG) --omit=dev
            inputs:
              command: custom
              customCommand: 'ci --cache $(NPM_CACHE_CONFIG) --omit=dev'
              workingDir: $(NPM_WORKING_DIR)
              customEndpoint: $(NPM_NEXUS_SERVICE_CONNECTION)

          - task: AWSShellScript@1
            displayName: deploy:dev
            inputs:
              awsCredentials: $(AWS_SERVICE_CONNECTION_DEV)
              regionName: 'eu-west-1'
              scriptType: 'inline'
              workingDirectory: $(NPM_WORKING_DIR)
              inlineScript: |
                npx cdk deploy --ci -c config=dev -c genericConfig=generic -c Repository=$(Build.Repository.Name) -c Pipeline=$(Build.DefinitionName) --all --require-approval never