variables:
  AWS_SERVICE_CONNECTION_DEV: aws-awsome-sbx # <<Fill in the name of your own service connection here>>
  NPM_NEXUS_SERVICE_CONNECTION: ns-npm-nexus
  # TODO: Change location to where your package.json is located, probably '.'
  WORKDIR: 'rest-api-public/typescript'

parameters:
  - name: environments
    displayName: Deployment Environments
    type: object
    default:
      - name: development
        aws_service_connection: aws-awsome-dev
        env: dev

trigger:
  branches:
    include:
      - '*'

resources:
  repositories:
    - repository: templates
      name: NSPAAS/azure-devops-templates
      type: git
      ref: master
    - repository: ns-shared-guard-rules
      type: git
      name: NSCAWS/ns-shared-guard-rules
    - repository: shared-templates
      name: NSPAAS/azure-devops-templates
      type: git
      ref: refs/tags/main_20220921.1

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build
    jobs:
      - job: Audit
        displayName: Audit
        steps:
          - task: npmAuthenticate@0
            displayName: "npm auth"
            inputs:
              workingFile: ${{ variables.WORKDIR }}/.npmrc
              customEndpoint: ns-npm-nexus
          - task: NodeTool@0
            displayName: 'Install Node.js'
            inputs:
              versionSpec: '16.x'
          - task: Npm@1
            displayName: 'npm ci'
            inputs:
              command: ci
              workingDir: ${{ variables.WORKDIR }}
          - task: Npm@1
            displayName: 'npm audit'
            inputs:
              command: custom
              customCommand: audit --audit-level=high --omit=dev
              workingDir: ${{ variables.WORKDIR }}
