# TODO: Fill in your account + region
AWSAccount: '921999976166'
AWSRegion: 'eu-west-1'

# TODO: TO REMOVE
Environment: dev

Parameters:
  #Domain: 'api.craws-o.cla.ns.nl'
  #BasePath: 'artists-api'

Tags:
  # TODO: Which values are required? (S, O, A, T of P)
  Environment: dev
