Parameters:

Tags:
  # TODO: https://nsdigitaal.sharepoint.com/sites/NSCloudWiki/SitePages/Tagging-strategie.aspx
  ApplicationServiceID: 'ASIDxxxxxxx'
  BOIT: 'boit'
  CIA: '111'
  Application: 'artists-api'
  Team: 'awsome'
  map-migrated: d-server-00tl810rxa1dds

  # TODO: TO REMOVE
  Department: 'ComIT'

# TODO: TO REMOVE
App: 'artists-api'
